### ISSUE TITLE
It would be cool to add a highlighter tool to the kreader application, how can I do?

### ISSUE THREAD

**Issue by mePy2** [onyx-intl/OnyxAndroidDemo#10]

**Comment by wangsuicheng** [comment]
Please describe your ideas in detail

**Comment by mePy2** [comment]
Hi,

I am happy you replied to this.

I think a **necessary tool** for the reader application of our boox is the highlighter:
![](https://www.yourdictionary.com/images/definitions/lg/7968.highlight.jpg)

Personally I am looking for a way to make this with the Screen. (I do not mind about the lag, I just want this to work. This mean that maybe I do not need the ScribbleDemo, since I think it could not fit my needs.)

**Comment by wangsuicheng** [comment]
As the different mode between pen and eraser,  we will develop it in the next version if possible

**Comment by mePy2** [comment]
I would like to help if possible.

I was thinking about integrating Boox pen capabilities with something like a modified/lighter version of https://github.com/koreader/koreader KOReader.

I have nothing done yet, but if you want I can keep you updated.

**Comment by joycode** [comment]
@mePy2 There is a highlight tool in the reader, so I'm closing this issue, if you still have questions, we can re-open this issue and have further discussion.

**Comment by mePy2** [comment]
@joycode thank you
