### ISSUE TITLE
Note and Library app

### ISSUE THREAD

**Issue by LecrisUT** [onyx-intl/OnyxAndroidDemo#19]
Is there any information available on where the notes are saved? I would like to access them with a 3rd-party sync app. Also can these be exported to `.pdf` file via script?

**Comment by asampal** [comment]
I poked around a bit but couldn't find the location. I would also be interested to know.

**Comment by joycode** [comment]
Note's data is saved in app's private data area, is not accessible from outside.
BTW, third party access is not supported any more.

**Comment by LecrisUT** [comment]
Honestly, with all the kernel not being shared, this lack of support for third party, and not considering open source standards like WebDav for syncing, I am completely regretting having purchased an Onyx product. I am looking forward to the PineNote so I can throw this away.
