### ISSUE TITLE
Examples not Opening

### ISSUE THREAD

**Issue by MrRSquared** [onyx-intl/OnyxAndroidDemo#24]
Hello,
I was able to build and install the OnyxDemo app on my Nova Pro, but none of the samples actually load. I am getting no errors in logcat, but the main window does not change. I am probably missing something, but what?

I am attempting to make a sortable note view app to create a gradebook for my classroom this year.

**Comment by MrRSquared** [comment]
After a lot of other work, it seems it is AndroidX that is breaking this.  I have been working off build 7931725 in the meantime. I am using a Nova Pro, so do not need AndroidX currently anyway.

**Comment by betaprior** [comment]
This is quite frustrating; it would be nice if the demo examples worked with the latest hardware (I have Note Air and am trying to develop for it).

**Comment by MrRSquared** [comment]
In doing the downgrade, does it support AndroidX? I concur. Gradle is annoying.

**Comment by joycode** [comment]
No problem with latest demo code, please try again.
