### ISSUE TITLE
请问下，PDF阅读怎么增加签批擦除功能？参考ScribbleMoveEraserDemoActivity会有问题，SurfaceView和PDFview有冲突

### ISSUE THREAD

**Issue by jiangwenfei** [onyx-intl/OnyxAndroidDemo#29]

**Comment by MrRSquared** [comment]
Hello, I wonder if this has a connection to what I just discovered. I am having difficulty implementing the eraser (point selection eraser) in an activity with multiple surfaceViews.

If you just want to erase the entire surface, you could use the method they trigger (they have two varieties) for the erase button.

Option 1 (like on the ScribbleMoveEraserDemoActivity)...
```
public void onEraserClick(){
        touchHelper.setRawDrawingEnabled(false);
        renderBitmap.eraseColor(Color.TRANSPARENT);
        drawBitmap(surfaceView);
        touchHelper.setRawDrawingEnabled(true);
    }
```
I think the method doing the heavy lifting here is the renderBitmap().
```
private void renderBitmap(Path path) {
        if (canvas == null) {
            return;
        }
        canvas.drawPath(path, getRenderPaint());
    }
```
This is also invoked by the individual point eraser, but with multiple surfaceviews, the individual eraser returns null for points, yet the eraser button, clears the screen. Odd right?

The other option for bulk erase is the clearScreen() method used in the ScribbleMultipleScribbleViewActivity.
```public void onEraserClick(){
        touchHelper.setRawDrawingEnabled(false);
        cleanSurfaceView(surfaceView1);
        cleanSurfaceView(surfaceView2);
        touchHelper.setRawDrawingEnabled(true);
    }```
Which invokes...
```private void cleanSurfaceView(SurfaceView surfaceView) {
        if (surfaceView.getHolder() == null) {
            return;
        }
        Canvas canvas = surfaceView.getHolder().lockCanvas();
        if (canvas == null) {
            return;
        }
        canvas.drawColor(Color.WHITE);
        surfaceView.getHolder().unlockCanvasAndPost(canvas);
    }
```

**Comment by MrRSquared** [comment]
Upon further investigation, it seems my eraser issue is different (the points are being returned correctly), but I am leaving my post above as it shows the two ways the SDK clears the screen. I thought it could help. If it does not, please someone let me know, or you can remove it yourself.

**Comment by joycode** [comment]
Eraser is expected to be implemented by App logic, before erasing, you need to quit raw drawing mode first, then redraw everything except paths being erased on the canvas.
