### ISSUE TITLE
NewShapeModel

### ISSUE THREAD

**Issue by gaborauth** [onyx-intl/OnyxAndroidDemo#47]
Hi,

I'm trying to extend the NoteDemoActivity, list the notes (it is working) but I cannot query pages and shapes.

This is working as documented:
`        noteProvider = RemoteNoteProvider()`
`        val notes = noteProvider.loadAllNoteList()`
`        notes.stream().forEach {`
`            Timber.i("%s (%s %s): %s [%d]", it.uniqueId, it.isLibrary, it.parentUniqueId, it.title, it.subDocCount)`
`        }`

But, I cannot load any shape based on any document unique id:
`        val newShapeModels = NewShapeDataProvider.loadShapeList("07ec191c-18ee-4d8a-9516-56b3a59448b3")`
`        Timber.i("ShapeModels: %d", newShapeModels.size)`

I always get zero result:
`ShapeModels: 0`

Do you have any example about pages and shapes?

**Comment by joycode** [comment]
Third party Note data access is not supported any more.
