### ISSUE TITLE
Creating a new note via an intent and in a certain folder

### ISSUE THREAD

**Issue by berkan** [onyx-intl/OnyxAndroidDemo#51]
Hello
 

Looking at [NoteDemoActivity.java#L117](https://github.com/onyx-intl/OnyxAndroidDemo/blob/ff8af87ec6dc407642f42f385efbc567c29f59d5/app/src/main/java/com/onyx/android/demo/note/NoteDemoActivity.java#L117), I figured how to create a new note via the "com.onyx.android.note.note.ui.ScribbleActivity" intent.

I also guessed that I can set the title of the note by including a json string like {“Title“: “hello  world“} as extra data.

Does anybody know what key should I use to specify the folder that the note should be created in? 

Many thanks,
Berkan

**Comment by joycode** [comment]
Third party Note data access is not supported any more.
