### ISSUE TITLE
Color selection on Nova 3 Color

### ISSUE THREAD

**Issue by abygm1** [onyx-intl/OnyxAndroidDemo#64]
Hi,

I am able to run the androidDemo successfully.  I tried changing pen color by editing code "paint.setColor(Color.RED)" in initPaint() but no effect.  Tried Normal mode and A2 mode.  Request to guide how to change pen color.
Thanks.

**Comment by Edward259** [comment]
com.onyx.android.sdk.pen.TouchHelper#setStrokeColor
