### ISSUE TITLE
RawInputCallback's methods never called

### ISSUE THREAD

**Issue by vzukanov** [onyx-intl/OnyxAndroidDemo#74]
When launching the tutorial app, navigating to Scribble Demo -> Scribble Touch Helper Demo and then drawing on the screen, netiher of the RawInputCallback's methods (defined [here](https://github.com/onyx-intl/OnyxAndroidDemo/blob/da2b1f1694239a20ee4dd8c84e8f7665126de09f/app/src/main/java/com/android/onyx/demo/scribble/ScribbleTouchHelperDemoActivity.java#L288)) get invoked.

Inside the app I'm building I experience a similar problem: can't get the raw inputs from the stylus. How can I be notified of these events?

**Comment by vzukanov** [comment]
Just in case you'll need it, attaching the information about the device I'm using.
![boox_info_1](https://user-images.githubusercontent.com/26735137/151691763-475f93b9-635d-4411-bb6f-2a65c1cc4996.png)
![boox_info_2](https://user-images.githubusercontent.com/26735137/151691765-3763af54-8693-4c81-b99a-23fc99eda20c.png)

**Comment by vzukanov** [comment]
Also tried to update the device to latest firmware, but the raw input callbacks still don't work. This is the updated OS:
![image](https://user-images.githubusercontent.com/26735137/151692964-be2443b4-8963-4099-82f4-ab91653493a3.png)

**Comment by vzukanov** [comment]
I also tested [PngNote app](https://github.com/karino2/PngNote) by @karino2. Found the same problem: raw input callback never called.

**Comment by vzukanov** [comment]
I tested the same APK on another Max Lumi 2 device and it works there as expected. So, this seems to be related to a specific device, which is really odd.
Is there any configuration which controls whether raw input notifications are sent to SDK users?

**Comment by onyx-chenhj** [comment]
@vzukanov  Hello, I guess your Max Lumi 2 version is October 27th, and there is this problem.
Please upgrade the firmware (after November 17th) and try again.
Thank you.

**Comment by vzukanov** [comment]
Can confirm that updating to firmware from Nov 18, 2021 solved this problem.
In this context, I find it surprising that when I updated device's firmware two weeks ago, it did not install this version, despite the fact that its "release date" is Nov 2021.
Closing this ticket.
